# -*- coding: utf-8 -*-
"""collabrative_filtering_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wRWjvJQ5h_S0jE5iRxcgZASCkIzcCkab
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col
from pyspark.ml.feature import StringIndexer
from pyspark.ml.recommendation import ALS
from pyspark.ml.evaluation import RegressionEvaluator

path = "s3://yelpgoldlayerdata/yelp data/gold_layer/ml/recommendation_features/"

df = spark.read.parquet(path)

df.printSchema()

print("Number of Rows :", df.count())

print("Columns :")
print(df.columns)

from pyspark.sql.functions import when, count

df.select([
    count(when(col(c).isNull(), c)).alias(c)
    for c in df.columns
]).show()

df = df.dropDuplicates()

from pyspark.ml.feature import StringIndexer

user_indexer = StringIndexer(
    inputCol="user_id",
    outputCol="userIndex"
)

user_model = user_indexer.fit(df)

df = user_model.transform(df)

business_indexer = StringIndexer(
    inputCol="business_id",
    outputCol="businessIndex"
)

business_model = business_indexer.fit(df)

df = business_model.transform(df)

from pyspark.sql.functions import col

df = df.withColumn(
    "userIndex",
    col("userIndex").cast("integer")
)

df = df.withColumn(
    "businessIndex",
    col("businessIndex").cast("integer")
)

ratings = df.select(
    col("userIndex"),
    col("businessIndex"),
    col("stars").alias("rating")
)

ratings.printSchema()

ratings.show(10, truncate=False)

train, test = ratings.randomSplit([0.8, 0.2], seed=42)

print("Training Rows :", train.count())
print("Testing Rows :", test.count())

from pyspark.ml.recommendation import ALS

als = ALS(
    userCol="userIndex",
    itemCol="businessIndex",
    ratingCol="rating",
    coldStartStrategy="drop",
    nonnegative=True,
    implicitPrefs=False,
    rank=20,
    maxIter=15,
    regParam=0.1
)

model = als.fit(train)

predictions = model.transform(test)

predictions.show(10, truncate=False)

from pyspark.ml.evaluation import RegressionEvaluator

evaluator = RegressionEvaluator(
    metricName="rmse",
    labelCol="rating",
    predictionCol="prediction"
)

rmse = evaluator.evaluate(predictions)

print("RMSE:", rmse)