# -*- coding: utf-8 -*-
"""collabrative_filtering_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wRWjvJQ5h_S0jE5iRxcgZASCkIzcCkab
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, when, count
from pyspark.ml.feature import StringIndexer
from pyspark.ml.recommendation import ALS
from pyspark.ml.evaluation import RegressionEvaluator


# ============================================================
# 1. CREATE SPARK SESSION
# ============================================================

spark = SparkSession.builder \
    .appName("Yelp Collaborative Filtering") \
    .getOrCreate()


# ============================================================
# 2. READ DATA FROM S3
# ============================================================

path = "s3://yelpgoldlayerdata/yelp data/gold_layer/ml/recommendation_features/"

df = spark.read.parquet(path)


# ============================================================
# 3. DATA INFORMATION
# ============================================================

df.printSchema()

print("Number of Rows:", df.count())

print("Columns:")
print(df.columns)


# ============================================================
# 4. CHECK NULL VALUES
# ============================================================

print("Null Values:")

df.select([
    count(
        when(col(c).isNull(), c)
    ).alias(c)
    for c in df.columns
]).show()


# ============================================================
# 5. REMOVE DUPLICATES
# ============================================================

df = df.dropDuplicates()

print("Rows after removing duplicates:", df.count())


# ============================================================
# 6. REMOVE RECORDS WITH NULL VALUES
# ============================================================

df = df.dropna(
    subset=["user_id", "business_id", "stars"]
)


# ============================================================
# 7. CONVERT STAR RATING TO DOUBLE
# ============================================================

df = df.withColumn(
    "stars",
    col("stars").cast("double")
)


# ============================================================
# 8. INDEX USER IDs
# ============================================================

user_indexer = StringIndexer(
    inputCol="user_id",
    outputCol="userIndex"
)

user_model = user_indexer.fit(df)

df = user_model.transform(df)


# ============================================================
# 9. INDEX BUSINESS IDs
# ============================================================

business_indexer = StringIndexer(
    inputCol="business_id",
    outputCol="businessIndex"
)

business_model = business_indexer.fit(df)

df = business_model.transform(df)


# ============================================================
# 10. CONVERT INDEXES TO INTEGER
# ============================================================

df = df.withColumn(
    "userIndex",
    col("userIndex").cast("integer")
)

df = df.withColumn(
    "businessIndex",
    col("businessIndex").cast("integer")
)


# ============================================================
# 11. CREATE RATINGS DATAFRAME
# ============================================================

ratings = df.select(
    col("userIndex"),
    col("businessIndex"),
    col("stars").alias("rating")
)


print("Ratings Schema:")
ratings.printSchema()

print("Sample Ratings:")
ratings.show(10, truncate=False)


# ============================================================
# 12. TRAIN-TEST SPLIT
# ============================================================

train, test = ratings.randomSplit(
    [0.8, 0.2],
    seed=42
)

print("Training Rows:", train.count())
print("Testing Rows:", test.count())


# ============================================================
# 13. CREATE ALS MODEL
# ============================================================

als = ALS(
    userCol="userIndex",
    itemCol="businessIndex",
    ratingCol="rating",

    # Remove predictions for users/items
    # that were not present during training
    coldStartStrategy="drop",

    # Ratings are explicit
    implicitPrefs=False,

    # Latent factors
    rank=20,

    # Number of iterations
    maxIter=15,

    # Regularization
    regParam=0.1,

    # Keep latent factors non-negative
    nonnegative=True,

    seed=42
)


# ============================================================
# 14. TRAIN MODEL
# ============================================================

print("Training ALS model...")

model = als.fit(train)

print("Model training completed.")


# ============================================================
# 15. MAKE PREDICTIONS
# ============================================================

predictions = model.transform(test)

print("Predictions:")

predictions.show(
    10,
    truncate=False
)


# ============================================================
# 16. EVALUATE MODEL USING RMSE
# ============================================================

evaluator = RegressionEvaluator(
    metricName="rmse",
    labelCol="rating",
    predictionCol="prediction"
)

rmse = evaluator.evaluate(predictions)

print("====================================")
print("RMSE:", rmse)
print("====================================")


# ============================================================
# 17. STOP SPARK
# ============================================================

spark.stop()
