# -*- coding: utf-8 -*-
"""sentiment_analysis_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KfOC70TeqhGeVijjeqq_ekJv8sXYm9mB
"""

Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("Yelp Sentiment Analysis") \
    .getOrCreate()

spark.sparkContext.setLogLevel("WARN")

Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark
print(spark.version)


Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark

file_path = "s3://yelpdatasetvita/gold_layer/ml/sentiment_features/part-00000-c3f61153-e06b-4f01-88ea-69e9a133a765-c000.snappy.parquet"

df = spark.read.parquet(file_path)

df.printSchema()

df.show(10, truncate=False)

Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark

from pyspark.sql.functions import col

df = df.select(
    col("review_text"),
    col("sentiment_label"),
    col("stars")
)

df.show(5)

Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark
df = df.na.drop(
    subset=[
        "review_text",
        "sentiment_label"
    ]
)


Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark
print(df.count())


Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark
from pyspark.sql.functions import lower, regexp_replace, trim

df = df.withColumn(
    "clean_text",
    lower(col("review_text"))
)

df = df.withColumn(
    "clean_text",
    regexp_replace("clean_text", r"http\\S+", "")
)

df = df.withColumn(
    "clean_text",
    regexp_replace("clean_text", "<[^>]*>", "")
)

df = df.withColumn(
    "clean_text",
    regexp_replace("clean_text", "[^a-zA-Z\\s]", "")
)

df = df.withColumn(
    "clean_text",
    trim(col("clean_text"))
)


Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark
df.select(
    "review_text",
    "clean_text"
).show(5, truncate=False)


Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark
from pyspark.ml.feature import StringIndexer

labelIndexer = StringIndexer(
    inputCol="sentiment_label",
    outputCol="label"
)

labelModel = labelIndexer.fit(df)

df = labelModel.transform(df)


Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark
from pyspark.ml.feature import Tokenizer

tokenizer = Tokenizer(
    inputCol="clean_text",
    outputCol="words"
)

df = tokenizer.transform(df)

df.select("clean_text", "words").show(5, truncate=False)


Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark
from pyspark.ml.feature import StopWordsRemover

remover = StopWordsRemover(
    inputCol="words",
    outputCol="filtered_words"
)

df = remover.transform(df)

df.select("filtered_words").show(5, truncate=False)


Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark
from pyspark.ml.feature import HashingTF

hashingTF = HashingTF(
    inputCol="filtered_words",
    outputCol="rawFeatures",
    numFeatures=20000
)

df = hashingTF.transform(df)

df.select("rawFeatures").show(5, truncate=False)


Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark
from pyspark.ml.feature import IDF

idf = IDF(
    inputCol="rawFeatures",
    outputCol="features"
)

idfModel = idf.fit(df)

df = idfModel.transform(df)

df.select("features").show(5, truncate=False)


Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark
train_df, test_df = df.randomSplit([0.8, 0.2], seed=42)

print("Training Records:", train_df.count())
print("Testing Records :", test_df.count())


Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark
from pyspark.ml.classification import LogisticRegression

lr = LogisticRegression(
    featuresCol="features",
    labelCol="label",
    maxIter=20
)

lr_model = lr.fit(train_df)


Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark
predictions = lr_model.transform(test_df)

predictions.select(
    "clean_text",
    "sentiment_label",
    "prediction"
).show(10, truncate=False)


Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark

from pyspark.ml.evaluation import MulticlassClassificationEvaluator

evaluator = MulticlassClassificationEvaluator(
    labelCol="label",
    predictionCol="prediction",
    metricName="accuracy"
)

accuracy = evaluator.evaluate(predictions)

print("Accuracy =", accuracy)

Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark
train_df, test_df = df.randomSplit([0.8, 0.2], seed=42)

print("Training Records:", train_df.count())
print("Testing Records :", test_df.count())


Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark

from pyspark.ml.classification import LogisticRegression

lr = LogisticRegression(
    featuresCol="features",
    labelCol="label",
    maxIter=20,
    regParam=0.0
)

lr_model = lr.fit(train_df)


Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark
predictions = lr_model.transform(test_df)

predictions.select(
    "clean_text",
    "sentiment_label",
    "label",
    "prediction",
    "probability"
).show(10, truncate=False)


Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark
from pyspark.ml.evaluation import MulticlassClassificationEvaluator

accuracy = MulticlassClassificationEvaluator(
    labelCol="label",
    predictionCol="prediction",
    metricName="accuracy"
).evaluate(predictions)

print("Accuracy:", accuracy)


Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark
f1 = MulticlassClassificationEvaluator(
    labelCol="label",
    predictionCol="prediction",
    metricName="f1"
).evaluate(predictions)

print("F1 Score:", f1)


Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark
lr_model.write().overwrite().save(
    "s3://yelpdatasetvita/gold_layer/sentiment_analysis_Model/"
)


Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark
predictions.write.mode("overwrite").parquet(
    "s3://yelpdatasetvita/gold_layer/sentiment_analysis_output/"
)


Commented out IPython magic to ensure Python compatibility.
%%pyspark default.spark

