# -*- coding: utf-8 -*-
"""collabrative_filterin_output.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_DPb0dCDSSSdtULdCLvutWE1BO5kd2MN
"""

# Commented out IPython magic to ensure Python compatibility.
# %%pyspark default.spark
# from pyspark.sql import SparkSession
# from pyspark.sql.functions import col
# from pyspark.ml.feature import StringIndexer
# from pyspark.ml.recommendation import ALS
# from pyspark.ml.evaluation import RegressionEvaluator
#

# Commented out IPython magic to ensure Python compatibility.
# %%pyspark default.spark
# path = "s3://yelpdatasetvita/gold_layer/ml/recommendation_features/"
# 
# df = spark.read.parquet(path)
#

# Commented out IPython magic to ensure Python compatibility.
# %%pyspark default.spark
# 
# print("Number of Rows :", df.count())

# Commented out IPython magic to ensure Python compatibility.
# %%pyspark default.spark
# print("Columns :")
# print(df.columns)
#

# Commented out IPython magic to ensure Python compatibility.
# %%pyspark default.spark
# from pyspark.sql.functions import when, count
# 
# df.select([
#     count(when(col(c).isNull(), c)).alias(c)
#     for c in df.columns
# ]).show()
#

# Commented out IPython magic to ensure Python compatibility.
# %%pyspark default.spark
# 
# df = df.dropDuplicates()

# Commented out IPython magic to ensure Python compatibility.
# %%pyspark default.spark
# 
# 
# from pyspark.sql.functions import monotonically_increasing_id
# 
# # Create user index
# users = (
#     df.select("user_id")
#       .distinct()
#       .withColumn("userIndex", monotonically_increasing_id())
# )
# 
# # Join back
# df = df.join(users, "user_id")
# 
# # Create business index
# business = (
#     df.select("business_id")
#       .distinct()
#       .withColumn("businessIndex", monotonically_increasing_id())
# )
# 
# df = df.join(business, "business_id")
# 
# df.show(5)

# Commented out IPython magic to ensure Python compatibility.
# %%pyspark default.spark
# from pyspark.sql.functions import monotonically_increasing_id
# 
# # Remove old businessIndex if it exists
# if "businessIndex" in df.columns:
#     df = df.drop("businessIndex")
# 
# # Create mapping
# business_mapping = (
#     df.select("business_id")
#       .distinct()
#       .withColumn("businessIndex", monotonically_increasing_id())
# )
# 
# # Join mapping back
# df = df.join(business_mapping, on="business_id", how="left")
# 
# # Check result
# df.select("business_id", "businessIndex").show(10, truncate=False)

# Commented out IPython magic to ensure Python compatibility.
# %%pyspark default.spark
# 
# from pyspark.sql.functions import col
# 
# df = df.withColumn(
#     "userIndex",
#     col("userIndex").cast("integer")
# )
# 
# df = df.withColumn(
#     "businessIndex",
#     col("businessIndex").cast("integer")
# )

# Commented out IPython magic to ensure Python compatibility.
# %%pyspark default.spark
# ratings = df.select(
#     col("userIndex"),
#     col("businessIndex"),
#     col("stars").alias("rating")
# )
#

# Commented out IPython magic to ensure Python compatibility.
# %%pyspark default.spark
# ratings.printSchema()
# 
# ratings.show(10, truncate=False)
#

# Commented out IPython magic to ensure Python compatibility.
# %%pyspark default.spark
# train, test = ratings.randomSplit([0.8, 0.2], seed=42)
# 
# print("Training Rows :", train.count())
# print("Testing Rows :", test.count())
#

# Commented out IPython magic to ensure Python compatibility.
# %%pyspark default.spark
# from pyspark.ml.recommendation import ALS
# 
# als = ALS(
#     userCol="userIndex",
#     itemCol="businessIndex",
#     ratingCol="rating",
#     coldStartStrategy="drop",
#     nonnegative=True,
#     implicitPrefs=False,
#     rank=20,
#     maxIter=20,
#     regParam=0.05
# )
#

# Commented out IPython magic to ensure Python compatibility.
# %%pyspark default.spark
# 
# model = als.fit(train)

# Commented out IPython magic to ensure Python compatibility.
# %%pyspark default.spark
# predictions = model.transform(test)
# 
# predictions.show(10, truncate=False)
#

# Commented out IPython magic to ensure Python compatibility.
# %%pyspark default.spark
# from pyspark.ml.evaluation import RegressionEvaluator
# 
# evaluator = RegressionEvaluator(
#     metricName="rmse",
#     labelCol="rating",
#     predictionCol="prediction"
# )
# 
# rmse = evaluator.evaluate(predictions)
# 
# print("RMSE:", rmse)
#

# Commented out IPython magic to ensure Python compatibility.
# %%pyspark default.spark
# 
# from pyspark.ml.recommendation import ALS
# from pyspark.ml.evaluation import RegressionEvaluator
# 
# evaluator = RegressionEvaluator(
#     metricName="rmse",
#     labelCol="rating",
#     predictionCol="prediction"
# )
# 
# best_rmse = float("inf")
# best_params = None
# 
# for rank in [10, 20, 30, 40, 50]:
#     for reg in [0.01, 0.05, 0.1, 0.15]:
#         als = ALS(
#             userCol="userIndex",
#             itemCol="businessIndex",
#             ratingCol="rating",
#             rank=rank,
#             regParam=reg,
#             maxIter=20,
#             coldStartStrategy="drop"
#         )
# 
#         model = als.fit(train)
#         predictions = model.transform(test)
#         rmse = evaluator.evaluate(predictions)
# 
#         print(f"Rank={rank}, Reg={reg}, RMSE={rmse:.4f}")
# 
#         if rmse < best_rmse:
#             best_rmse = rmse
#             best_params = (rank, reg)
# 
# print("\nBest RMSE:", best_rmse)
# print("Best Parameters:", best_params)

# Commented out IPython magic to ensure Python compatibility.
# %%pyspark default.spark
# predictions.show(20, truncate=False)

# Commented out IPython magic to ensure Python compatibility.
# %%pyspark default.spark
# predictions = model.transform(test)
# 
# predictions.write \
#     .mode("overwrite") \
#     .parquet("s3://yelpdatasetvita/gold_layer/collabrative_filtering_output/predictions/")

# Commented out IPython magic to ensure Python compatibility.
# %%pyspark default.spark
# 
#